@WebApi_HostAddress = http://localhost:5001

POST {{WebApi_HostAddress}}/api/users/create
Accept: application/json
Content-Type: application/json

{
    "UserName": "Zainab",
    "UserPassword": "1234",
    "UserEmail": "Zainab@ruc"
}

###

PUT {{WebApi_HostAddress}}/api/users/login
Accept: application/json
Content-Type: application/json

{
    "UserName": "Test",
    "Password": "test"
}

###

POST {{WebApi_HostAddress}}/api/users/bookmarkName
Accept: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVGVzdCIsImV4cCI6MTczMDgwNjQwNn0.PnyW0rqZUODV04hrsYdav506aP_hOFu26h96yODrvis
Content-Type: application/json
{
    "nameId" : "nm0000156"
}

###

DELETE {{WebApi_HostAddress}}/api/users/deletebookmarName
Accept: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVGVzdCIsImV4cCI6MTczMDgwNjQwNn0.PnyW0rqZUODV04hrsYdav506aP_hOFu26h96yODrvis
Content-Type: application/json
{
    "nameId" : "nm0000156"
}

###

POST {{WebApi_HostAddress}}/api/users/bookmarkTitle
Accept: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVGVzdCIsImV4cCI6MTczMDgwNjQwNn0.PnyW0rqZUODV04hrsYdav506aP_hOFu26h96yODrvis
Content-Type: application/json
{
    "TitleId" : "tt25154648"
}

###
DELETE {{WebApi_HostAddress}}/api/users/deletebookmarkTitle
Accept: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVGVzdCIsImV4cCI6MTczMDgwNjQwNn0.PnyW0rqZUODV04hrsYdav506aP_hOFu26h96yODrvis
Content-Type: application/json
{
    "TitleId" : "tt25154648"
}

###

POST {{WebApi_HostAddress}}/api/users/rateName
Accept: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVGVzdCIsImV4cCI6MTczMDgwNjQwNn0.PnyW0rqZUODV04hrsYdav506aP_hOFu26h96yODrvis
Content-Type: application/json
{
    "nameId" :  "nm0000129",
    "Rate" : 9
}

###

POST {{WebApi_HostAddress}}/api/users/rateTitle
Accept: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVGVzdCIsImV4cCI6MTczMDgwNjQwNn0.PnyW0rqZUODV04hrsYdav506aP_hOFu26h96yODrvis
Content-Type: application/json
{
    "TitleId" :  "tt32467748",
    "Rate" : 9
}