@WebApi_HostAddress = http://localhost:5001

POST {{WebApi_HostAddress}}/api/users
Accept: application/json
Content-Type: application/json

{
    "UserName": "Zainab",
    "UserPassword": "1234",
    "UserEmail": "Zainab@ruc"
}

###

PUT {{WebApi_HostAddress}}/api/users
Accept: application/json
Content-Type: application/json

{
    "UserName": "Zainab",
    "Password": "1234"
}

###

